add "stable" encoding
The first pass mode was a huge success, encoding a ton of stuff in just
a few days. I've been experimenting more with upscaling settings, and I
think there's a happy medium here using the hqdn3d filter instead of
nlmeans. nlmeans is the better filter, and it's noticeable if you
output compare frame by frame, but it's REALLY SLOW! I'll save that for
after I get everything encoded to a moderate degree of quality.

diff --git a/allinone/utils b/allinone/utils
--- a/allinone/utils
+++ b/allinone/utils
@@ -6,7 +6,7 @@
 #
 
 die() {
-  echo "ERROR: $1" >&2
+  echo -e "ERROR: $1" >&2
   exit 1
 }
 
